--Create a database with two tables:
CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT,
EMP_FIRSTNAME VARCHAR,
EMP_LASTNAME VARCHAR,
DEPARTMENT_ID INT,
SALARY INT,
EMP_EMAIL VARCHAR,
);

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR,
);

--Create a sequence and trigger to auto-generate primary key values for both tables. 

CREATE SEQUENCE forEmployee
start with 1
increment by 1
minvalue 0
maxvalue 10
cycle;

CREATE SEQUENCE forDepartment
start with 1
increment by 1
minvalue 0
maxvalue 5
cycle;

--Insert at least six employees and three departments. 

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 1, 'Ronald', 'Dobson',1,'50000','rondob@hotmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 2, 'Mark', 'Ronson',1,'150000','markron@hotmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 3, 'Dub', 'Hue',3,'40000','dubh@hotmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 4, 'Nuke', 'Hubble',2,'20000','nuhu@gmail.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 5, 'Elvin', 'Gladly',3,'40000','elg@aol.com');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL) VALUES ( 6, 'Marko', 'Dugood',2,'30000','markymark@gmail.com');

INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 1, 'Music');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 2, 'Theater');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES ( 3, 'Design');